// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAhkHEFE-EmgDNuz4R-QfA0FXS1VJ7ijzE',
    appId: '1:133575437865:web:79770ac89bdaadb114b638',
    messagingSenderId: '133575437865',
    projectId: 'nourelman -app',
    authDomain: 'nourelman -app.firebaseapp.com',
    storageBucket: 'nourelman -app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCigQenFQP-46ZFm7BR4Vww8OxSdy35LSs',
    appId: '1:133575437865:android:259fd384ede8c58714b638',
    messagingSenderId: '133575437865',
    projectId: 'nourelman -app',
    storageBucket: 'nourelman -app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDFCkN9YClTFrdtgfj3oMkLGkrS2LqubGU',
    appId: '1:133575437865:ios:1bd05cd371f05cad14b638',
    messagingSenderId: '133575437865',
    projectId: 'nourelman -app',
    storageBucket: 'nourelman -app.firebasestorage.app',
    iosBundleId: 'com.example.project1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDFCkN9YClTFrdtgfj3oMkLGkrS2LqubGU',
    appId: '1:133575437865:ios:1bd05cd371f05cad14b638',
    messagingSenderId: '133575437865',
    projectId: 'nourelman -app',
    storageBucket: 'nourelman -app.firebasestorage.app',
    iosBundleId: 'com.example.project1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAhkHEFE-EmgDNuz4R-QfA0FXS1VJ7ijzE',
    appId: '1:133575437865:web:07f494c6df02246614b638',
    messagingSenderId: '133575437865',
    projectId: 'nourelman -app',
    authDomain: 'nourelman -app.firebaseapp.com',
    storageBucket: 'nourelman -app.firebasestorage.app',
  );
}
